# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8936ebca68d81c3e2e3551bcb6bf3cefcf6aa50dd5f36883c6dec747102a4d3f687b11420f22905ef3738630b507afa8f3ebaf64ae8549253dd4335b71970dcc
  pusher_app_id: '97866'
  pusher_key:    '19e125826e0fe9165bae'
  pusher_secret: '97b6ee92eeca12664241'

test:
  secret_key_base: 451ac4bfeaa68094e510739c7fbbe6e34ebe4814ea99f1d75deae47c032bbab6e45fd78fa38ba7099eaf3a8c9a84a0264d448494fdfe4cfead0a846db4df9f84
  pusher_app_id: '97866'
  pusher_key:    '19e125826e0fe9165bae'
  pusher_secret: '97b6ee92eeca12664241'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
